---
output: 
    html_document:
        css: style.css
---

```{r setup, include=FALSE}
load_all()
library(pander)
library(tidyverse)
panderOptions('knitr.auto.asis', FALSE)
panderOptions('keep.line.breaks', TRUE)
panderOptions('table.alignment.rownames', 'left')
```
```{r load_data, include=FALSE}
load("~/Desktop/temp.RData")
#flux_df <- load_sandflux(area, start_date, end_date)
```

```{r sandmass, include=FALSE}
source("~/code/owensReports/scripts/sandmass.R")
```

```{r sandflux, include=FALSE}
source("~/code/owensReports/scripts/sandflux.R")
```

```{r wetness, include=FALSE}
source("~/code/owensReports/scripts/swir_wetness.R")
```

```{r output, echo=F, results='asis'}
for (i in unique(csc_mass$dca)){
    report_header(start_date, end_date, report_date, area)
    cat(paste0(" \n# ", i, " \n"))
    gridExtra::grid.arrange(mass_grobs[[i]], flux_grobs[[i]], ncol=2)
    cat(" \n")
    cat(" \n## Monthly Sand Reduction Control Efficiency \n")
    tbl_mass <- mass_ce %>% filter(dca==i) 
    colnames(tbl_mass) <- c("DCA", "Treatment", "Avg. Sand Mass\\\n(g)", 
                            "Control Efficiency")
    pandoc.table(tbl_mass)
    cat(" \n## Daily Sand Flux Reduction Control Efficiency \n")
    tbl_flux <- flux_ce %>% filter(dca==i) 
    if (nrow(tbl_flux)==0){
        cat(" \n\nNo days with average daily flux in control area > 1 g/cm^2/day.")
    } else{
    colnames(tbl_flux) <- c("DCA", "Date", 
                            "0% Target\\\nAvg. Daily Flux\\\n(g/cm^2/day)", 
                            "CE\\\n(45% Target)",
                            "CE\\\n(55% Target)",
                            "CE\\\n(65% Target)", 
                            "CE\\\n(75% Target)")
    pandoc.table(tbl_flux, split.table=Inf)
    }
    cat("<p style=\"page-break-after:always;\"></p> \n")
    report_header(start_date, end_date, report_date, area)
    cat(paste0(" \n# ", i, " \n"))
    print(dcas[[i]]$wet_plot)
    cat(" \n")
    cat(" \n## SWIR Estimated Wetness \n")
    tbl_wet <- wetness %>% filter(dca==i)
    colnames(tbl_wet) <- c("DCA", "Target Wetness", "SWIR Estimated\nWetness")
    pandoc.table(tbl_wet)
    cat("<p style=\"page-break-after:always;\"></p> \n")
}
```

